### Create new place
POST http://localhost:5000/api/places/
Content-Type: application/json

{
  "title": "Empire State Building",
  "description": "One of the most famous sky scrapers in the world!",
  "address": "20 W 34th St, New York, NY 10001",
  "creator": "u1"
}

### Read (get) a place by it's id
GET http://localhost:5000/api/places/61ef2d2d84655e674213b5f6

### Read (get) a place by it's USER id
GET http://localhost:5000/api/places/user/u1

### Update place by id
PATCH http://localhost:5000/api/places/61f159883488701591f1f79d
Content-Type: application/json

{
  "title": "update one",
  "description": "test scrapers in the world!"
}

### Delete place by it's id
DELETE http://localhost:5000/api/places/61f159883488701591f1f79d